apiVersion: v1
kind: Namespace
metadata:
 name: node-app
---
apiVersion: v1
kind: Service
metadata:
  name:  node-app-service
  namespace: node-app
spec:
  type: LoadBalancer
  selector:
    app: node-app
  ports:
  - name: web-port
    protocol: TCP
    # service port
    port: 3000
    # pod port
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-dep
  namespace: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  node-app
  template:
    metadata:
      labels:
        app:  node-app
    spec:
      containers:
      - name:  node-app
        image: satish2797/node-web-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000